apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-pod
  ports:
    - name: rest
      protocol: TCP
      port: 8002
      targetPort: 8002
    - name: grpc
      protocol: TCP
      port: 18081
      targetPort: 18081
