// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HousekeeperServiceClient is the client API for HousekeeperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HousekeeperServiceClient interface {
	GetHousekeeperByUuid(ctx context.Context, in *GetHousekeeperRequest, opts ...grpc.CallOption) (*Housekeeper, error)
	GetAllHousekeepers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HousekeeperList, error)
}

type housekeeperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHousekeeperServiceClient(cc grpc.ClientConnInterface) HousekeeperServiceClient {
	return &housekeeperServiceClient{cc}
}

func (c *housekeeperServiceClient) GetHousekeeperByUuid(ctx context.Context, in *GetHousekeeperRequest, opts ...grpc.CallOption) (*Housekeeper, error) {
	out := new(Housekeeper)
	err := c.cc.Invoke(ctx, "/HousekeeperService/GetHousekeeperByUuid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *housekeeperServiceClient) GetAllHousekeepers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HousekeeperList, error) {
	out := new(HousekeeperList)
	err := c.cc.Invoke(ctx, "/HousekeeperService/GetAllHousekeepers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HousekeeperServiceServer is the server API for HousekeeperService service.
// All implementations must embed UnimplementedHousekeeperServiceServer
// for forward compatibility
type HousekeeperServiceServer interface {
	GetHousekeeperByUuid(context.Context, *GetHousekeeperRequest) (*Housekeeper, error)
	GetAllHousekeepers(context.Context, *Empty) (*HousekeeperList, error)
	mustEmbedUnimplementedHousekeeperServiceServer()
}

// UnimplementedHousekeeperServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHousekeeperServiceServer struct {
}

func (UnimplementedHousekeeperServiceServer) GetHousekeeperByUuid(context.Context, *GetHousekeeperRequest) (*Housekeeper, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHousekeeperByUuid not implemented")
}
func (UnimplementedHousekeeperServiceServer) GetAllHousekeepers(context.Context, *Empty) (*HousekeeperList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllHousekeepers not implemented")
}
func (UnimplementedHousekeeperServiceServer) mustEmbedUnimplementedHousekeeperServiceServer() {}

// UnsafeHousekeeperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HousekeeperServiceServer will
// result in compilation errors.
type UnsafeHousekeeperServiceServer interface {
	mustEmbedUnimplementedHousekeeperServiceServer()
}

func RegisterHousekeeperServiceServer(s grpc.ServiceRegistrar, srv HousekeeperServiceServer) {
	s.RegisterService(&HousekeeperService_ServiceDesc, srv)
}

func _HousekeeperService_GetHousekeeperByUuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHousekeeperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HousekeeperServiceServer).GetHousekeeperByUuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HousekeeperService/GetHousekeeperByUuid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HousekeeperServiceServer).GetHousekeeperByUuid(ctx, req.(*GetHousekeeperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HousekeeperService_GetAllHousekeepers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HousekeeperServiceServer).GetAllHousekeepers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HousekeeperService/GetAllHousekeepers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HousekeeperServiceServer).GetAllHousekeepers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// HousekeeperService_ServiceDesc is the grpc.ServiceDesc for HousekeeperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HousekeeperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HousekeeperService",
	HandlerType: (*HousekeeperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHousekeeperByUuid",
			Handler:    _HousekeeperService_GetHousekeeperByUuid_Handler,
		},
		{
			MethodName: "GetAllHousekeepers",
			Handler:    _HousekeeperService_GetAllHousekeepers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/housekeeper.proto",
}
