version: "3.9"

services:
  # admin-service ------------------------------------
  admin_postgres:
    image: postgres:13
    restart: always
    volumes:
      - database-storage-admin:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: admin_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  admin_service:
    image: champkub6/admin-service:v1.0.0
    build:
      context: ./admin_service
    depends_on:
      - admin_postgres
    environment:
      SV_PORT: 8080
      DB_HOST: admin_postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: admin_db
      JWT_SECRET: ADMIN_SERVICE_SECRET_KEY
      JWT_EXPIRES_MINUTES: 60
    ports:
      - 8080:8080
  # customer-service ------------------------------------
  customer_postgres:
    image: postgres:13
    restart: always
    volumes:
      - database-storage-customer:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5431:5432
  customer_service:
    image: champkub6/customer-service:v1.0.0
    build:
      context: ./customer_service
    depends_on:
      - customer_postgres
    environment:
      DATABASE_HOST: customer_postgres
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      DATABASE_NAME: customer_db
      DATABASE_URL: postgresql://user:password@customer_postgres:5432/customer_db?sslmode=disable
      JWT_SECRET: CUSTOMER_SERVICE_SECRET_KEY
      SERVER_PORT: 8082
      JWT_EXPIRES_MINUTES: 60
    ports:
      - 8082:8082
  # housekeeper-service ------------------------------------
  housekeeper_postgres:
    image: postgres:13
    restart: always
    volumes:
      - database-storage-housekeeper:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: housekeeper_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5434:5432
  housekeeper_service:
    image: champkub6/housekeeper-service:v1.0.0
    build:
      context: ./housekeeper_service
    depends_on:
      - housekeeper_postgres
    environment:
      SV_PORT: 8083
      DB_HOST: housekeeper_postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWOR: password
      DB_NAME: housekeeper_db
      JWT_SECRET: HOUSEKEEPER_SERVICE_SECRET_KEY
      JWT_EXPIRES_MINUTES: 60
    ports:
      - 8083:8083
  # appointment-service ------------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  app_kafka:
    image: confluentinc/cp-kafka:latest
    container_name: app_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://app_kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false" # Disable auto-creating topics
    command:
      - /bin/sh
      - -c
      - |
        # Start Kafka server
        /etc/confluent/docker/run &
        # Wait for Kafka to be ready (port to be open)
        while ! nc -z localhost 9092; do sleep 1; done
        # Create initial topic
        kafka-topics --create --if-not-exists --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 --topic create_appointment
        # Tail logs to keep the container running
        tail -f /dev/null

  app_mongodb:
    image: mongo:latest
    ports:
      - "27016:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

  app_postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - database-storage-appointment:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appointment_db

  appointment_service:
    image: champkub6/appointment-service:v1.1.0
    build:
      context: ./appointment_service
    depends_on:
      - zookeeper
      - app_kafka
      - app_mongodb
      - app_postgres
    environment:
      HTTPPort: 8081
      DB_HOST: app_postgres
      DB_PORT: 5432
      DB_USER: user
      DB_NAME: appointment_db
      DB_PASSWORD: password
      DB_SSLMODE: disable
      POSTGRES_DSN: postgres://user:password@app_postgres:5432/appointment_db?sslmode=disable
      MONGO_DSN: mongodb://user:password@app_mongodb:27017
      MONGO_DB_NAME: appointment_service
      KAFKA_BROKER: app_kafka:9092
      CUSTOMER_SERVICE_GRPC_HOST: customer_service:18081
      HOUSEKEEPER_SERVICE_GRPC_HOST: housekeeper_service:18082
    ports:
      - 8081:8081

  # api-gateway ------------------------------------
  api-gateway:
    image: champkub6/api-gateway:v1.0.0
    build:
      context: ./api-gateway
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      KAFKA_HOST: app_kafka:9092
      EXAMPLE_URI: http://localhost:4000
      EXAMPLE_SECRET: hehe
      ADMIN_URI: http://admin_service:8080
      ADMIN_SECRET: ADMIN_SERVICE_SECRET_KEY
      CUSTOMER_URI: http://customer_service:8082
      CUSTOMER_SECRET: CUSTOMER_SERVICE_SECRET_KEY
      HOUSEKEEPER_URI: http://housekeeper_service:8083
      HOUSEKEEPER_SECRET: HOUSEKEEPER_SERVICE_SECRET_KEY
      APPOINTMENT_URI: http://appointment_service:8081
      # ADMIN_UI: http://localhost:15000
      # HOUSEKEEPER_UI: http://localhost:15000
      # CUSTOMER_UI: http://localhost:15000,http://localhost:25000

volumes:
  database-storage-admin:
  database-storage-customer:
  database-storage-housekeeper:
  database-storage-appointment:
  mongodb_data:
