version: '3.9'

services:
  database:
    image: postgres:13.3-alpine
    restart: always 
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mhan-baeh
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

volumes:
  database-storage:
