apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-pod
  template:
    metadata:
      labels:
        app: kafka-pod
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper:3.4.6
          ports:
            - containerPort: 2181
        - name: kafka
          image: wurstmeister/kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INSIDE://kafka:9093,OUTSIDE://localhost:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            - name: KAFKA_LISTENERS
              value: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INSIDE
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_CREATE_TOPICS
              value: "create_appointment:1:1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          volumeMounts:
            - name: kafka-data
              mountPath: /var/run/docker.sock
      volumes:
        - name: kafka-data
          hostPath:
            path: /var/run/docker.sock
