apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-admin-pod
  template:
    metadata:
      labels:
        app: web-admin-pod
    spec:
      containers: 
        - name: web-admin
          image: natthaphons/web-admin:5.0.0
          ports:
            - containerPort: 5003
          env:

