FROM node:20.8-slim

ARG REACT_APP_BACKEND_API

# ENV REACT_APP_BACKEND_API=http://a80522e8e4d8b4220875a6beaed61a73-1241861906.ap-southeast-1.elb.amazonaws.com/api
ENV REACT_APP_BACKEND_API=http://localhost:3000
ADD . /home/web

WORKDIR /home/web

ENV TZ=Asia/Bangkok
ENV PORT=5001

RUN apt-get update && apt-get install -y curl

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone

RUN npm install

RUN npm run build

RUN npm install -g serve

EXPOSE 5001

CMD serve -s build
