// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: housekeeper.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// import "google/protobuf/empty.proto"; // Import the empty.proto file
type Housekeeper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname string `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname  string `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Phone     string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *Housekeeper) Reset() {
	*x = Housekeeper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housekeeper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Housekeeper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Housekeeper) ProtoMessage() {}

func (x *Housekeeper) ProtoReflect() protoreflect.Message {
	mi := &file_housekeeper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Housekeeper.ProtoReflect.Descriptor instead.
func (*Housekeeper) Descriptor() ([]byte, []int) {
	return file_housekeeper_proto_rawDescGZIP(), []int{0}
}

func (x *Housekeeper) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Housekeeper) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *Housekeeper) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *Housekeeper) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type CreateHousekeeperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Firstname string `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname  string `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Phone     string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *CreateHousekeeperRequest) Reset() {
	*x = CreateHousekeeperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housekeeper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHousekeeperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHousekeeperRequest) ProtoMessage() {}

func (x *CreateHousekeeperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housekeeper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHousekeeperRequest.ProtoReflect.Descriptor instead.
func (*CreateHousekeeperRequest) Descriptor() ([]byte, []int) {
	return file_housekeeper_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHousekeeperRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *CreateHousekeeperRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *CreateHousekeeperRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetHousekeeperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetHousekeeperRequest) Reset() {
	*x = GetHousekeeperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housekeeper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHousekeeperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHousekeeperRequest) ProtoMessage() {}

func (x *GetHousekeeperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housekeeper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHousekeeperRequest.ProtoReflect.Descriptor instead.
func (*GetHousekeeperRequest) Descriptor() ([]byte, []int) {
	return file_housekeeper_proto_rawDescGZIP(), []int{2}
}

func (x *GetHousekeeperRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HousekeeperList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Housekeepers []*Housekeeper `protobuf:"bytes,1,rep,name=housekeepers,proto3" json:"housekeepers,omitempty"`
}

func (x *HousekeeperList) Reset() {
	*x = HousekeeperList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housekeeper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HousekeeperList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HousekeeperList) ProtoMessage() {}

func (x *HousekeeperList) ProtoReflect() protoreflect.Message {
	mi := &file_housekeeper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HousekeeperList.ProtoReflect.Descriptor instead.
func (*HousekeeperList) Descriptor() ([]byte, []int) {
	return file_housekeeper_proto_rawDescGZIP(), []int{3}
}

func (x *HousekeeperList) GetHousekeepers() []*Housekeeper {
	if x != nil {
		return x.Housekeepers
	}
	return nil
}

type GetAllHousekeeperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllHousekeeperRequest) Reset() {
	*x = GetAllHousekeeperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housekeeper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllHousekeeperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHousekeeperRequest) ProtoMessage() {}

func (x *GetAllHousekeeperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housekeeper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHousekeeperRequest.ProtoReflect.Descriptor instead.
func (*GetAllHousekeeperRequest) Descriptor() ([]byte, []int) {
	return file_housekeeper_proto_rawDescGZIP(), []int{4}
}

type UpdateHousekeeperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Housekeeper *Housekeeper `protobuf:"bytes,2,opt,name=housekeeper,proto3" json:"housekeeper,omitempty"`
}

func (x *UpdateHousekeeperRequest) Reset() {
	*x = UpdateHousekeeperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housekeeper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHousekeeperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHousekeeperRequest) ProtoMessage() {}

func (x *UpdateHousekeeperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housekeeper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHousekeeperRequest.ProtoReflect.Descriptor instead.
func (*UpdateHousekeeperRequest) Descriptor() ([]byte, []int) {
	return file_housekeeper_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateHousekeeperRequest) GetHousekeeper() *Housekeeper {
	if x != nil {
		return x.Housekeeper
	}
	return nil
}

type DeleteHousekeeperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteHousekeeperRequest) Reset() {
	*x = DeleteHousekeeperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housekeeper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHousekeeperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHousekeeperRequest) ProtoMessage() {}

func (x *DeleteHousekeeperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housekeeper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHousekeeperRequest.ProtoReflect.Descriptor instead.
func (*DeleteHousekeeperRequest) Descriptor() ([]byte, []int) {
	return file_housekeeper_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteHousekeeperRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteHousekeeperResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteHousekeeperResponse) Reset() {
	*x = DeleteHousekeeperResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housekeeper_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHousekeeperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHousekeeperResponse) ProtoMessage() {}

func (x *DeleteHousekeeperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housekeeper_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHousekeeperResponse.ProtoReflect.Descriptor instead.
func (*DeleteHousekeeperResponse) Descriptor() ([]byte, []int) {
	return file_housekeeper_proto_rawDescGZIP(), []int{7}
}

var File_housekeeper_proto protoreflect.FileDescriptor

var file_housekeeper_proto_rawDesc = []byte{
	0x0a, 0x11, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x0b, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x22, 0x6a, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x27,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x0f, 0x48, 0x6f, 0x75, 0x73, 0x65,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0c, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x52, 0x0c,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x73, 0x22, 0x1a, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x52, 0x0b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f,
	0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x1b, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd7, 0x02,
	0x0a, 0x12, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f,
	0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x12, 0x36, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x48,
	0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x73,
	0x12, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x48, 0x6f,
	0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3c, 0x0a,
	0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x12, 0x19, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x75, 0x73, 0x65,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x11, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x12, 0x19, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_housekeeper_proto_rawDescOnce sync.Once
	file_housekeeper_proto_rawDescData = file_housekeeper_proto_rawDesc
)

func file_housekeeper_proto_rawDescGZIP() []byte {
	file_housekeeper_proto_rawDescOnce.Do(func() {
		file_housekeeper_proto_rawDescData = protoimpl.X.CompressGZIP(file_housekeeper_proto_rawDescData)
	})
	return file_housekeeper_proto_rawDescData
}

var file_housekeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_housekeeper_proto_goTypes = []interface{}{
	(*Housekeeper)(nil),               // 0: Housekeeper
	(*CreateHousekeeperRequest)(nil),  // 1: CreateHousekeeperRequest
	(*GetHousekeeperRequest)(nil),     // 2: GetHousekeeperRequest
	(*HousekeeperList)(nil),           // 3: HousekeeperList
	(*GetAllHousekeeperRequest)(nil),  // 4: GetAllHousekeeperRequest
	(*UpdateHousekeeperRequest)(nil),  // 5: UpdateHousekeeperRequest
	(*DeleteHousekeeperRequest)(nil),  // 6: DeleteHousekeeperRequest
	(*DeleteHousekeeperResponse)(nil), // 7: DeleteHousekeeperResponse
}
var file_housekeeper_proto_depIdxs = []int32{
	0, // 0: HousekeeperList.housekeepers:type_name -> Housekeeper
	0, // 1: UpdateHousekeeperRequest.housekeeper:type_name -> Housekeeper
	1, // 2: HousekeeperService.CreateHousekeeper:input_type -> CreateHousekeeperRequest
	2, // 3: HousekeeperService.GetHousekeeper:input_type -> GetHousekeeperRequest
	4, // 4: HousekeeperService.GetAllHousekeepers:input_type -> GetAllHousekeeperRequest
	5, // 5: HousekeeperService.UpdateHousekeeper:input_type -> UpdateHousekeeperRequest
	6, // 6: HousekeeperService.DeleteHousekeeper:input_type -> DeleteHousekeeperRequest
	0, // 7: HousekeeperService.CreateHousekeeper:output_type -> Housekeeper
	0, // 8: HousekeeperService.GetHousekeeper:output_type -> Housekeeper
	3, // 9: HousekeeperService.GetAllHousekeepers:output_type -> HousekeeperList
	0, // 10: HousekeeperService.UpdateHousekeeper:output_type -> Housekeeper
	7, // 11: HousekeeperService.DeleteHousekeeper:output_type -> DeleteHousekeeperResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_housekeeper_proto_init() }
func file_housekeeper_proto_init() {
	if File_housekeeper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_housekeeper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Housekeeper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housekeeper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHousekeeperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housekeeper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHousekeeperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housekeeper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HousekeeperList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housekeeper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllHousekeeperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housekeeper_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHousekeeperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housekeeper_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHousekeeperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housekeeper_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHousekeeperResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_housekeeper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_housekeeper_proto_goTypes,
		DependencyIndexes: file_housekeeper_proto_depIdxs,
		MessageInfos:      file_housekeeper_proto_msgTypes,
	}.Build()
	File_housekeeper_proto = out.File
	file_housekeeper_proto_rawDesc = nil
	file_housekeeper_proto_goTypes = nil
	file_housekeeper_proto_depIdxs = nil
}
