version: '3.7'

services:
  database:
    image: postgres:15
    restart: always 
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: housekeeper_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5434:5432

volumes:
  database-storage: