apiVersion: apps/v1
kind: Deployment
metadata:
  name: housekeeper-deployment
  labels:
    app: housekeeper-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: housekeeper-pod
  template:
    metadata:
      labels:
        app: housekeeper-pod
    spec:
      containers:
        - name: housekeeper
          image: champkub6/housekeeper-service
          ports:
            - containerPort: 8083
          env:
            - name: SV_PORT
              value: "8083"
            - name: DB_HOST
              value: housekeeper_postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: user
            - name: DB_PASSWORD
              value: password
            - name: DB_NAME
              value: housekeeper_db
            - name: JWT_SECRET
              value: HOUSEKEEPER_SERVICE_SECRET_KEY




